# -*- coding: utf-8 -*-
"""DSBDA3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n3SNGkR5cTXlQdEEY1ZpnQsm9PW2PUrn
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = sns.load_dataset('tips')

df.head()

df.shape

df.info()

df.isnull().sum()

df.describe()

df['time'].value_counts()

df.groupby('smoker').describe()

df.groupby('smoker')[['total_bill','tip']].describe()

df['sex'].value_counts()

df.groupby('sex').describe()

df.groupby('sex')[['total_bill','tip']].describe()

df.groupby('day').describe()

df.groupby('day')[['total_bill','tip']].describe()

df[df['day']=='Sun']['total_bill'].describe()

df1 = sns.load_dataset('iris')

df1.head()

df1.shape

df1.info()

df.describe()

df1.isnull().sum()

df1['species'].value_counts()

df1.groupby('species')['sepal_length'].describe()

df1.groupby('species')['sepal_width'].describe()

df1.groupby('species')['petal_length'].describe()

df1.groupby('species')['petal_width'].describe()

df1.groupby('species')['petal_width'].quantile(0.25)

