# -*- coding: utf-8 -*-
"""DSBDA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iat5Y0D_-HNE-VX8VuXhLDNu6RnPMBks
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance - StudentsPerformance.csv")

df.head()

df.describe()

df.shape

df.info()

df.isnull().sum()

df['reading score'].fillna(df['reading score'].mean(), inplace = True)

df['writing score'].fillna(df['writing score'].median(), inplace = True)



df.isnull().sum()

df['gender'].value_counts()

df['gender'].fillna('female', inplace = True)

df.isnull().sum()

df['race/ethnicity'].fillna(method = 'bfill', inplace = True)

df['lunch'].fillna(method = 'ffill', inplace = True)

df['test preparation course'].fillna(method = 'backfill', inplace = True)

df.isnull().sum()

df.boxplot()



# Inter Quartile Function
def Replace(col):
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  upper = Q3 + (1.5*IQR)
  lower = Q1 - (1.5*IQR)
  np.clip(df[col], lower, upper, inplace=True)

Replace('math score')

Replace('reading score')

Replace('writing score')

df.boxplot()
plt.show()

sns.kdeplot(df)

df['math score'].skew()

df['reading score'].skew()



df['writing score'].skew()

from sklearn.preprocessing import MinMaxScaler, StandardScaler

Scaler = StandardScaler()

Scaler.fit(df[['math score']])

df['math_score_scaler']=Scaler.transform(df[['math score']])

df['math_score_scaler']

Minmax = MinMaxScaler()

Minmax.fit(df[['math score']])

df['math_score_minmax'] = Minmax.transform(df[['math score']])

df['math_score_minmax']

