# -*- coding: utf-8 -*-
"""DSBDA10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4zHlH_dCqNvW3gVcabOqLnlJYLDaxsa
"""

import pandas as pd
import numpy as np
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

df = sns.load_dataset('iris')

df.shape

df.head()

df.info()

df.describe()

df.isnull().sum()

df.dtypes







sns.histplot(df['sepal_length'])

sns.kdeplot(df['sepal_length'])





















sns.distplot(df['sepal_length'])