# -*- coding: utf-8 -*-
"""DSBDA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NqvyeYI_FRBeN830tnvSAwNVvio4KITy
"""

import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/housing.csv')

data.head()

data.info()

data.describe()

data.sample(10)

data.columns

#gives the shape of the dataset i.e. (rows, columns)
data.shape

#slicing data from 15 to 55
sliced_data = data[15:55]

#selecting and displaying only specific columns
specific_cols = data[["CRIM", "AGE"]]
print(specific_cols)

